### ISSUE TITLE
Need a way to easily add event details

### ISSUE THREAD

**Issue by pranav-bhatt** [dscpesu/DSC-PESU#10]
This i think is the major deterrent to the downfall of this project IMO. Its time consuming to add stuff each time we have a workshop. 

So lets create a secret button, or a cheat code of sorts(event listener) to take us to a special page to add stuff when we are done with an event. Cause implementing a login system is too much effort!

Open for discussion!

**Comment by varungupta3009** [comment]
There's already a Konami for Login that I had added, but then again, there is no use of a login, or anything, here... This messes again with Issue #4, because, if we only run on static hosting like GH Pages or Netlify, there is no way of adding dynamic content or login or custom posts...

Once the hosting issue is fixed, we can easily move onto dynamic stuff like #7 or #8.

**Comment by pranav-bhatt** [comment]
yeah i saw the codebase and realised, thats why i closed
